/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Kutyapackage;

import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;
import java.io.*;
import javax.swing.JOptionPane;
import javax.swing.text.html.parser.DTDConstants;

/**
 *
 * @author Tomi
 */
public class KutyaForm extends javax.swing.JFrame {
    
    static ArrayList<KutyaClass> kutyak = new ArrayList<>();
    static DefaultTableModel tblmodel;

    /**
     * Creates new form KutyaForm
     */
    public KutyaForm() {
        initComponents();
        this.tblmodel = (DefaultTableModel) tblAdatok.getModel();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnBetoltes = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblAdatok = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        cbHanyKutya = new javax.swing.JComboBox<>();
        txtNev = new javax.swing.JTextField();
        txtFajta = new javax.swing.JTextField();
        txtNem = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtEletkor = new javax.swing.JTextField();
        txtHanyKutya = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("A kutyák adatai");

        btnBetoltes.setText("Az adatok betöltése");
        btnBetoltes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBetoltesActionPerformed(evt);
            }
        });

        tblAdatok.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "A kutya neve", "A kutya fajtája:"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblAdatok.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblAdatokMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblAdatok);

        jLabel2.setText("A kiválasztott kutyák adatai:");

        jLabel3.setText("Név:");

        jLabel4.setText("Fajta:");

        jLabel5.setText("Neme:");

        jLabel6.setText("Hány kutya van nemek szerint?");

        cbHanyKutya.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbHanyKutyaActionPerformed(evt);
            }
        });

        jLabel7.setText("Életkora:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnBetoltes, javax.swing.GroupLayout.PREFERRED_SIZE, 439, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 556, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel5))
                                .addGap(64, 64, 64)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(txtNev, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 153, Short.MAX_VALUE)
                                    .addComponent(txtFajta)
                                    .addComponent(txtNem)
                                    .addComponent(txtEletkor))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(cbHanyKutya, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtHanyKutya, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(55, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(btnBetoltes))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtNev, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtFajta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addGap(15, 15, 15)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtNem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtEletkor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(18, 18, 18)
                        .addComponent(cbHanyKutya, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtHanyKutya, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(36, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBetoltesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBetoltesActionPerformed
        try {
           FileReader fajl = new FileReader ("kutyak.txt");
           BufferedReader br = new BufferedReader(fajl);
           String sor = "";
            while ((sor = br.readLine()) != null) {                
                KutyaClass k = new KutyaClass(sor);
                kutyak.add(k);
            }
            
            br.close();
            fajl.close();
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Hiba a beolvasáskor!");
        }
        btnBetoltes.setEnabled(false);
        insertTable();
        
        insertCombobox();
    }//GEN-LAST:event_btnBetoltesActionPerformed

    private void cbHanyKutyaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbHanyKutyaActionPerformed
        // TODO add your handling code here:
        
        
        int db = 0;
        for (KutyaClass hk : kutyak) {
            if (hk.getNem().equals(cbHanyKutya.getSelectedItem().toString())) {
                db++;
            }
        }
        
        txtHanyKutya.setText(String.valueOf(db));
    }//GEN-LAST:event_cbHanyKutyaActionPerformed

    private void tblAdatokMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblAdatokMouseClicked
        // TODO add your handling code here:
        int index = tblAdatok.getSelectedRow();
        
        //String faj = tblmodel.getValueAt(index, 0).toString();
        //String neme = tblmodel.getValueAt(index, 1).toString();
        //String eletkora = tblmodel.getValueAt(index, 2).toString();
        //String neve = tblmodel.getValueAt(index, 3).toString();
        
        txtFajta.setText(kutyak.get(index).getFajta());
        txtNem.setText(kutyak.get(index).getNem());
        txtEletkor.setText(String.valueOf(kutyak.get(index).getEletkor()));
        txtNev.setText(kutyak.get(index).getNev());
        
        
    }//GEN-LAST:event_tblAdatokMouseClicked

    /**
     * @param args the command line arguments
     */
    
    
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(KutyaForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(KutyaForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(KutyaForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(KutyaForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        
        

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new KutyaForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBetoltes;
    private javax.swing.JComboBox<String> cbHanyKutya;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblAdatok;
    private javax.swing.JTextField txtEletkor;
    private javax.swing.JTextField txtFajta;
    private javax.swing.JTextField txtHanyKutya;
    private javax.swing.JTextField txtNem;
    private javax.swing.JTextField txtNev;
    // End of variables declaration//GEN-END:variables

    private void insertTable() {
        
        for (KutyaClass k : kutyak) {
            tblmodel.addRow(new Object[]{k.getNev(),k.getFajta()});
        }
    }

    private void insertCombobox() {
        
        ArrayList<String> nemek = new ArrayList<>();
        for (KutyaClass kn : kutyak) {
            if (!nemek.contains((kn.getNem()))) {
                nemek.add(kn.getNem());
            }
        }
        
        for (String szk : nemek) {
            cbHanyKutya.addItem(szk);
        }

    }
}
